version: "3.8"

networks:
  www-network:
    name: ${COMPOSE_PROJECT_NAME}-network

services:
  webserver:
    build:
      context: ./bin/${PHPVERSION}
    container_name: "${COMPOSE_PROJECT_NAME}-${PHPVERSION}"
    restart: "always"
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html:rw
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
      - ${XDEBUG_LOG_DIR}:/var/log/xdebug
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=localhost
    restart: always
    volumes:
      - /sessions
      - ${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    depends_on:
        - database

  database:
    image: mariadb:latest
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    restart: always 
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
      - MEMORY_LIMIT=${MEMORY_LIMIT}

